### ISSUE TITLE
Asus Bluetooth and Wifi adapters not working

### ISSUE THREAD

**Issue by mario-64** [MrLightgun/MiSTerSindenDriver#4]
I've been using an Asus USB-BT500 Bluetooth adapter with MiSTer for many months without issue. However, after applying the Sinden MiSTer main and kernel the adapter is no longer recognized. This means  wireless mouse, keyboard and gamepad support is broken. Could you please fix this? Thank you, and also thank you for finally getting Sinden working with MiSTer.

Additionally, my Asus USB wifi adapter is also not working.

EDIT: Just saw that this is listed as a known issue. Will close when an update is released which fixes it.

**Comment by MrLightgun** [comment]
Hi, @mario-64 thanks for the feedback, should be fixed within 24 hours.

**Comment by thesunnymachine** [comment]
All Bluetooth Adapters for me are no longer working after installing.

**Comment by MrLightgun** [comment]
I believe the issue is now fixed, please use the updated kernel or start the process again which will get the updated kernel this time.  Please feedback if the issue is resolved if you can.

**Comment by thesunnymachine** [comment]
> I believe the issue is now fixed, please use the updated kernel or start the process again which will get the updated kernel this time. Please feedback if the issue is resolved if you can.

Update fixed BT for me.  But the Install script and Setup script are still not working.   

Install script won't write LIB files with the - read only - error still happening, and it installs the old broken kernel over the new one. 

Setup script just wont run 
![image](https://github.com/MrLightgun/MiSTerSindenDriver/assets/72642350/41180982-05b3-4ad4-ac48-bad1e8312bae)

**Comment by mario-64** [comment]
Closing as this issue has been resolved.
